#!/usr/bin/env ruby --disable-gems

cwd = File.expand_path(File.dirname(__FILE__))

unless ENV['IN_NIX_SHELL']
  require 'shellwords'
  exec("nix-shell #{cwd}/../default.nix --command './scripts/test-in_memory-watch #{ARGV.shelljoin}'")
end

unless ARGV.count == 1
  puts "Usage: test-in_memory-watch <fuzzy-name>"
  exit(1)
end

Dir.chdir("gems/in_memory") do
  exec("find lib test -name '*.rb' | entr -c ./bin/tests-run")
end