#!/usr/bin/env ruby --disable-gems

cwd = File.expand_path(File.dirname(__FILE__))

unless ENV['IN_NIX_SHELL']
  require 'shellwords'
  exec("nix-shell #{cwd}/../default.nix --command './scripts/test-in_memory-run #{ARGV.shelljoin}'")
end

Dir.chdir("gems/in_memory") do
  system("./bin/tests-run")
end